### ISSUE TITLE
How should I start using it?

### ISSUE THREAD

**Issue by dofine** [croqaz/img-db#2]
Thank you for the great work. I tried to clone the repo, but didn't know how to run the script.

**Comment by croqaz** [comment]
Hi @dofine ! Thanks for trying this project.
I'm the only one that uses this, as far as I know, so I never thought how somebody else would use it, sorry for not explaining it too well in the docs!
First of all, you need to install all dependencies.
I usually run `poetry shell` , `poetry install`.
You can also try `pip install .` inside the root of the project.

You have a few to run the CLI app:
- if you called "poetry install", you can already call `imgdb` inside the poetry shell
- you can call `poetry run imgdb ...` which basically does the same thing, but you don't need a shell
- if you don't use Poetry, you can call the main code with `python -m imgdb ...`, eg: `python -m imgdb add 'Pictures/iPhone8/' -o 'Pictures/archive/' --dbname imgdb.htm`

Let me know if that works for you!
TODO for me: update the docs.

**Comment by dofine** [comment]
> Hi @dofine ! Thanks for trying this project. I'm the only one that uses this, as far as I know, so I never thought how somebody else would use it, sorry for not explaining it too well in the docs! First of all, you need to install all dependencies. I usually run `poetry shell` , `poetry install`. You can also try `pip install .` inside the root of the project.
> 
> You have a few to run the CLI app:
> 
> * if you called "poetry install", you can already call `imgdb` inside the poetry shell
> * you can call `poetry run imgdb ...` which basically does the same thing, but you don't need a shell
> * if you don't use Poetry, you can call the main code with `python -m imgdb ...`, eg: `python -m imgdb add 'Pictures/iPhone8/' -o 'Pictures/archive/' --dbname imgdb.htm`
> 
> Let me know if that works for you! TODO for me: update the docs.

It works! My python knowledge is very limited, and I tried `python imgdb add` but forgot the `-m` flag. 
Also `poetry` is new to me. Nice to learn something new. Thanks!
